version: '3.4'

services:
  tagsapi:
    image: tagsapi
    container_name: tagsapi
    build:
      context: ./tagsapi/
      dockerfile: ./Dockerfile
    links:
      - "backend:db"
    ports:
      - 8080:8080

  backend:
    image: postgres:13.7-alpine
    container_name: pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432

    volumes:
      - ./backend/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    container_name: admfe

    ports:
      - 8081:8080

    links:
      - "backend:db"